#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CANSLIM打分 + 缠论/波浪/楔形/顶底山峰多维度过滤 + HTML报告生成
"""
import csv
import os
from datetime import datetime

# ========== 数据区 ==========
TODAY = "20260928"
PREV_CLOSE_DATE = "2026-09-24"

# 大盘分析（已确认）
MARKET_STATUS = {
    "trend": "空头排列",
    "ma200": "跌破（上证约3888 vs 估算MA200~4000）",
    "chanlun": "中枢下破，无一买",
    "wave": "4浪深调或A浪",
    "position_limit": 50,  # %
}

# A股候选（带形态分析推断）
A_SHARE_CANDIDATES = [
    {
        "code": "002847", "name": "盐津铺子", "market": "A股",
        "c_profit_yoy": 25.86,  # CANSLIM-C
        "a_cagr_3y": 48.66,     # CANSLIM-A
        "a_roe": 36.82,
        "n_catalyst": "短保烘焙新品+线下渠道扩张",
        "mkt_cap_yi": 105.2,    # CANSLIM-S
        "l_rps": 78,            # CANSLIM-L
        "north_inflow": True,   # CANSLIM-I
        # 形态分析
        "pattern": "下跌楔形收敛末端",
        "pattern_detail": "9月16日低点42.94后缩量横盘，楔形下轨收敛，等待放量突破",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【42.5, 46.3】",
            "position": "中枢下沿附近震荡",
            "buy_point": "中枢震荡类二买（回踩不破中枢下沿）",
            "buy_type": "二买/三买临界",
        },
        "wave": {
            "position": "主升浪3浪回调到位",
            "detail": "7月28日涨停+10%见阶段顶51，ABC调整浪A浪51→43完成，B浪反弹46→C浪进行中(43附近)",
        },
        "peak_bottom": "阶段新低后缩量企稳MA20，回踩MA10不破",
        "close_924": 43.15, "change_924": -0.12, "volume_ratio": 0.58,
        "buy_range": "43.0-44.5", "stop_loss": 39.7, "observe": "站上46.3放量突破",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 20, "N": 12, "L": 15, "S": 10, "I": 10, "形态": 8},
        "canslim_total": 95,
        "industry": "食品加工",
    },
    {
        "code": "600550", "name": "保变电气", "market": "A股",
        "c_profit_yoy": 34.63,
        "a_cagr_3y": 60.0,
        "a_roe": 27.44,
        "n_catalyst": "特高压变压器订单+出海",
        "mkt_cap_yi": 189.5,
        "l_rps": 72,
        "north_inflow": True,
        "pattern": "收敛平台整理，放量突破在即",
        "pattern_detail": "9月18日放量+2.16%涨停后回踩，平台10.3-11.0收敛",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【10.2, 11.0】",
            "position": "中枢下沿蓄势",
            "buy_point": "三买（回踩不破中枢，次级别背驰）",
            "buy_type": "三买",
        },
        "wave": {
            "position": "主升浪2浪回调完成",
            "detail": "9月9日起1浪上涨10.98→11.05，2浪回调至10.29完成，酝酿3浪",
        },
        "peak_bottom": "阶段新低后连续两天缩量企稳，量能萎缩至地量",
        "close_924": 10.29, "change_924": -1.06, "volume_ratio": 0.69,
        "buy_range": "10.3-10.8", "stop_loss": 9.47, "observe": "放量站上11.0",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 20, "N": 13, "L": 14, "S": 10, "I": 10, "形态": 9},
        "canslim_total": 96,
        "industry": "输变电设备",
    },
    {
        "code": "600961", "name": "株冶集团", "market": "A股",
        "c_profit_yoy": 99.71,
        "a_cagr_3y": 50.17,
        "a_roe": 31.40,
        "n_catalyst": "锌价上行+产能释放+电池材料",
        "mkt_cap_yi": 253.3,
        "l_rps": 68,
        "north_inflow": True,
        "pattern": "高位楔形回调接近支撑",
        "pattern_detail": "8月25日放量暴跌-6.2%，但60日线23附近有强支撑，形成下跌楔形",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【24.5, 28.0】",
            "position": "跌破中枢下沿，观察二买",
            "buy_point": "一买候选（下跌背驰确认中）",
            "buy_type": "一买候选",
        },
        "wave": {
            "position": "4浪回调末端",
            "detail": "10浪推动中30.17→23.61回调约22%，ABC调整接近尾声",
        },
        "peak_bottom": "8月25日放量急跌-6.2%后缩量横盘，23.6-24.5构筑短期底部",
        "close_924": 23.61, "change_924": -3.51, "volume_ratio": 0.78,
        "buy_range": "23.5-24.5", "stop_loss": 21.72, "observe": "重返25以上",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 18, "N": 14, "L": 13, "S": 10, "I": 10, "形态": 7},
        "canslim_total": 92,
        "industry": "有色金属/锌",
    },
    {
        "code": "603766", "name": "隆鑫通用", "market": "A股",
        "c_profit_yoy": 48.88,
        "a_cagr_3y": 44.5,
        "a_roe": 17.50,
        "n_catalyst": "通用动力+无人机",
        "mkt_cap_yi": 298.8,
        "l_rps": 82,
        "north_inflow": True,
        "pattern": "上涨楔形蓄势",
        "pattern_detail": "8月24日放量暴涨+5.12%后连续缩量回踩，量能萎缩，典型顶底山峰买点",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【13.5, 14.8】",
            "position": "中枢上沿震荡偏强",
            "buy_point": "中枢震荡三买（回踩不破中枢上沿）",
            "buy_type": "三买",
        },
        "wave": {
            "position": "主升浪3浪起点",
            "detail": "8月14日低点13.09→8月24日高点14.8为1浪，2浪回调14.55完成",
        },
        "peak_bottom": "8月24日放量拉升后缩量回踩MA10/MA20双支撑企稳，典型顶底山峰",
        "close_924": 14.55, "change_924": -0.07, "volume_ratio": 0.52,
        "buy_range": "14.4-14.9", "stop_loss": 13.39, "observe": "放量突破14.85",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 18, "N": 14, "L": 15, "S": 10, "I": 10, "形态": 10},
        "canslim_total": 97,
        "industry": "通用机械",
    },
    {
        "code": "689009", "name": "九号公司", "market": "A股",
        "c_profit_yoy": 63.48,
        "a_cagr_3y": 47.8,
        "a_roe": 26.08,
        "n_catalyst": "电动滑板车全球领先+出海",
        "mkt_cap_yi": 208.4,
        "l_rps": 80,
        "north_inflow": True,
        "pattern": "底部反转楔形",
        "pattern_detail": "9月16日见阶段低后连续3天缩量企稳，量能地量后放量预期",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【20.0, 22.8】",
            "position": "中枢下沿二次探底不破",
            "buy_point": "二买（不破低点，次级别MACD金叉）",
            "buy_type": "二买",
        },
        "wave": {
            "position": "主升浪4浪回调到位",
            "detail": "21.5→18.9回调12%，接近0.618位，ABC调整完成",
        },
        "peak_bottom": "9月16日低点18.85后回踩MA20企稳，缩量至地量",
        "close_924": 19.50, "change_924": -2.10, "volume_ratio": 0.65,
        "buy_range": "19.3-20.2", "stop_loss": 17.74, "observe": "重返21以上放量",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 19, "N": 13, "L": 14, "S": 10, "I": 10, "形态": 9},
        "canslim_total": 95,
        "industry": "短交通",
    },
]

# 港股通候选
HK_CANDIDATES = [
    {
        "code": "00700", "name": "腾讯控股", "market": "港股通",
        "c_profit_yoy": 15,
        "a_cagr_3y": 18,
        "a_roe": 18,
        "n_catalyst": "微信AI智能体+视频号商业化",
        "mkt_cap_yi_hkd": 35000,
        "l_rps": 68,
        "north_inflow": True,
        "pattern": "收敛三角形整理接近末端",
        "pattern_detail": "年线附近缩量整理，三角形收敛，等待突破方向",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【360, 400】",
            "position": "中枢中轴震荡",
            "buy_point": "中枢震荡三买",
            "buy_type": "三买",
        },
        "wave": {
            "position": "ABC调整浪B浪",
            "detail": "430→340为A浪，340→380为B浪反弹中，待C浪完成",
        },
        "peak_bottom": "340附近放量止跌，回踩MA20企稳",
        "close_924": 378.50, "change_924": 1.20, "volume_ratio": 0.80,
        "buy_range": "370-390", "stop_loss": 348.22, "observe": "突破400放量",
        "position_pct": 10,
        "canslim_detail": {"C": 18, "A": 15, "N": 15, "L": 14, "S": 10, "I": 10, "形态": 7},
        "canslim_total": 89,
        "industry": "互联网科技",
    },
    {
        "code": "02020", "name": "安踏体育", "market": "港股通",
        "c_profit_yoy": 25,
        "a_cagr_3y": 22,
        "a_roe": 20,
        "n_catalyst": "多品牌矩阵+海外扩张",
        "mkt_cap_yi_hkd": 3500,
        "l_rps": 85,
        "north_inflow": True,
        "pattern": "上升楔形健康",
        "pattern_detail": "主升通道内，缩量回踩MA20是介入良机",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【70, 82】",
            "position": "中枢上沿健康运行",
            "buy_point": "三买（回踩MA20不破中枢）",
            "buy_type": "三买",
        },
        "wave": {
            "position": "主升浪3浪中后段",
            "detail": "65→83为1浪，2浪回调70，3浪推进中80→新高",
        },
        "peak_bottom": "缩量回踩MA10/MA20双支撑后放量上攻",
        "close_924": 78.20, "change_924": -0.85, "volume_ratio": 0.60,
        "buy_range": "76-80", "stop_loss": 71.94, "observe": "突破82.5放量",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 18, "N": 14, "L": 15, "S": 10, "I": 10, "形态": 9},
        "canslim_total": 96,
        "industry": "体育用品",
    },
    {
        "code": "01024", "name": "快手-W", "market": "港股通",
        "c_profit_yoy": 40,
        "a_cagr_3y": 35,
        "a_roe": 15,
        "n_catalyst": "电商变现+短剧+AI内容",
        "mkt_cap_yi_hkd": 3500,
        "l_rps": 72,
        "north_inflow": True,
        "pattern": "底部反转形态",
        "pattern_detail": "长期底部区域放量突破颈线44，确立底部反转",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【40, 46】",
            "position": "中枢上沿突破后回踩",
            "buy_point": "三买（突破后缩量回踩不破中枢）",
            "buy_type": "三买",
        },
        "wave": {
            "position": "主升浪1浪末端/2浪回调起点",
            "detail": "33→47为1浪，2浪回调44→40",
        },
        "peak_bottom": "47附近放量后缩量回踩MA10企稳",
        "close_924": 44.80, "change_924": -1.30, "volume_ratio": 0.70,
        "buy_range": "44-46", "stop_loss": 41.22, "observe": "突破47放量",
        "position_pct": 10,
        "canslim_detail": {"C": 20, "A": 17, "N": 15, "L": 14, "S": 10, "I": 9, "形态": 8},
        "canslim_total": 93,
        "industry": "短视频/电商",
    },
    {
        "code": "01810", "name": "小米集团-W", "market": "港股通",
        "c_profit_yoy": 18,
        "a_cagr_3y": 20,
        "a_roe": 14,
        "n_catalyst": "汽车业务+手机高端化+IoT",
        "mkt_cap_yi_hkd": 40000,
        "l_rps": 74,
        "north_inflow": True,
        "pattern": "箱体蓄势整理",
        "pattern_detail": "26-30区间横盘蓄势，箱体下沿26.5附近买",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【26.5, 29.5】",
            "position": "中枢震荡",
            "buy_point": "中枢二买（下沿不破，背驰确认）",
            "buy_type": "二买",
        },
        "wave": {
            "position": "主升浪2浪回调末端",
            "detail": "22→30为1浪，2浪回调29→26.5完成，蓄势3浪",
        },
        "peak_bottom": "26.5附近连续放量止跌，构筑短期底部",
        "close_924": 27.40, "change_924": 0.50, "volume_ratio": 0.65,
        "buy_range": "26.5-28.0", "stop_loss": 25.21, "observe": "突破30放量",
        "position_pct": 10,
        "canslim_detail": {"C": 18, "A": 16, "N": 14, "L": 14, "S": 10, "I": 10, "形态": 8},
        "canslim_total": 90,
        "industry": "消费电子/汽车",
    },
    {
        "code": "03690", "name": "美团-W", "market": "港股通",
        "c_profit_yoy": 22,
        "a_cagr_3y": 25,
        "a_roe": 16,
        "n_catalyst": "即时零售+本地生活+AI配送",
        "mkt_cap_yi_hkd": 11640,
        "l_rps": 68,
        "north_inflow": True,
        "pattern": "下跌楔形收敛",
        "pattern_detail": "高位180→130下跌楔形收敛末端，下沿130附近强支撑",
        "chanlun": {
            "level": "日线",
            "zhongshu": "【130, 155】",
            "position": "中枢下沿反复确认",
            "buy_point": "一买候选（下跌背驰+级别扩张）",
            "buy_type": "一买候选",
        },
        "wave": {
            "position": "4浪回调末端/ABC调整完成",
            "detail": "180→130回调28%，已超0.618回撤位，C浪末端",
        },
        "peak_bottom": "130附近多次放量止跌，构筑W底雏形",
        "close_924": 132.50, "change_924": -2.10, "volume_ratio": 0.75,
        "buy_range": "130-138", "stop_loss": 121.90, "observe": "重返150放量",
        "position_pct": 10,
        "canslim_detail": {"C": 19, "A": 17, "N": 14, "L": 13, "S": 10, "I": 10, "形态": 7},
        "canslim_total": 90,
        "industry": "本地生活",
    },
]

# 合并最终10支（A股5+港股5）
FINAL_10 = A_SHARE_CANDIDATES + HK_CANDIDATES

